create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[0]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[1]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[2]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[3]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[4]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[5]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[6]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/din[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[0]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[1]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[2]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[3]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[4]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[5]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[6]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/dout[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[0]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[1]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[2]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[3]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[4]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[5]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[6]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[7]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[8]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[9]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[10]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/din[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[0]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[1]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[2]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[3]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[4]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[5]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[6]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[7]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[8]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[9]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[10]} {design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/dout[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/rd_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo0/wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axi_compression_0/U0/axi_compression_v1_0_S00_AXI_inst/fifo1/rd_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
