# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir X:/final_project_sim/lzw/lzw.cache/wt [current_project]
set_property parent.project_path X:/final_project_sim/lzw/lzw.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo x:/final_project_sim/lzw/lzw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096.xci
set_property is_locked true [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir X:/final_project_sim/lzw/lzw.runs/bram_4096_synth_1 -new_name bram_4096 -ip [get_ips bram_4096]]

if { $cached_ip eq {} } {

synth_design -top bram_4096 -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix bram_4096_ bram_4096.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bram_4096_stub.v
 lappend ipCachedFiles bram_4096_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bram_4096_stub.vhdl
 lappend ipCachedFiles bram_4096_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bram_4096_sim_netlist.v
 lappend ipCachedFiles bram_4096_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bram_4096_sim_netlist.vhdl
 lappend ipCachedFiles bram_4096_sim_netlist.vhdl

 config_ip_cache -add -dcp bram_4096.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips bram_4096]
}

rename_ref -prefix_all bram_4096_

write_checkpoint -force -noxdef bram_4096.dcp

catch { report_utilization -file bram_4096_utilization_synth.rpt -pb bram_4096_utilization_synth.pb }

if { [catch {
  file copy -force X:/final_project_sim/lzw/lzw.runs/bram_4096_synth_1/bram_4096.dcp X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force X:/final_project_sim/lzw/lzw.runs/bram_4096_synth_1/bram_4096.dcp X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force X:/final_project_sim/lzw/lzw.runs/bram_4096_synth_1/bram_4096_stub.v X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force X:/final_project_sim/lzw/lzw.runs/bram_4096_synth_1/bram_4096_stub.vhdl X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force X:/final_project_sim/lzw/lzw.runs/bram_4096_synth_1/bram_4096_sim_netlist.v X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force X:/final_project_sim/lzw/lzw.runs/bram_4096_synth_1/bram_4096_sim_netlist.vhdl X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir X:/final_project_sim/lzw/lzw.ip_user_files/ip/bram_4096]} {
  catch { 
    file copy -force X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_stub.v X:/final_project_sim/lzw/lzw.ip_user_files/ip/bram_4096
  }
}

if {[file isdir X:/final_project_sim/lzw/lzw.ip_user_files/ip/bram_4096]} {
  catch { 
    file copy -force X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096_stub.vhdl X:/final_project_sim/lzw/lzw.ip_user_files/ip/bram_4096
  }
}
