# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir X:/final_project_sim/lzw/lzw.cache/wt [current_project]
set_property parent.project_path X:/final_project_sim/lzw/lzw.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo x:/final_project_sim/lzw/lzw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/coe/bram1.coe
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/coe/bram2_0.coe
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/coe/bram2_1.coe
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/coe/bram4_0.coe
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/coe/bram4_1.coe
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/coe/bram4_3.coe
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/lzw/coe/bram4_2.coe
add_files X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/lzw/coe/bram4_3.coe
add_files -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096.dcp
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_4096/bram_4096.dcp]
add_files -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_2048_0/bram_2048_0.dcp
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_2048_0/bram_2048_0.dcp]
add_files -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_2048_1/bram_2048_1.dcp
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_2048_1/bram_2048_1.dcp]
add_files -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_1/bram_1024_1.dcp
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_1/bram_1024_1.dcp]
add_files -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_2/bram_1024_2.dcp
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_2/bram_1024_2.dcp]
add_files -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_3/bram_1024_3.dcp
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_3/bram_1024_3.dcp]
add_files -quiet X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_0/bram_1024_0.dcp
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_0/bram_1024_0.dcp]
read_vhdl -library xil_defaultlib {
  X:/final_project_sim/lzw/lzw.srcs/sources_1/new/dictionary_block_4.vhd
  X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/temp/dictionary_block_2.vhd
  X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/temp/dictionary_block.vhd
  X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/temp/dictionary_2.vhd
  X:/final_project_sim/lzw/lzw.srcs/sources_1/new/dictionary_4.vhd
  X:/final_project_sim/lzw/lzw.srcs/sources_1/imports/temp/lzw.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc X:/final_project_sim/lzw/lzw.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files X:/final_project_sim/lzw/lzw.srcs/constrs_1/new/constraints.xdc]


synth_design -top lzw -part xc7z020clg484-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef lzw.dcp

catch { report_utilization -file lzw_utilization_synth.rpt -pb lzw_utilization_synth.pb }
