# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_1/bram_1024_1.xci
# IP: The module: 'bram_1024_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_1/bram_1024_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_1024_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: X:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_1/bram_1024_1.xci
# IP: The module: 'bram_1024_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/final_project_sim/lzw/lzw.srcs/sources_1/ip/bram_1024_1/bram_1024_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_1024_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
